### ISSUE TITLE
Error: no such file 'main.ui'

### ISSUE THREAD

**Issue by guinslym** [a358003542/quicktikz#1]
Hi had this error while installing your package

```
(root) ➜  ~ quicktikz                 
Traceback (most recent call last):
  File "/home/guinslym/anaconda3/bin/quicktikz", line 11, in <module>
    sys.exit(gui())
  File "/home/guinslym/anaconda3/lib/python3.6/site-packages/quicktikz/main.py", line 17, in gui
    mainwindow = MainWindow()
  File "/home/guinslym/anaconda3/lib/python3.6/site-packages/quicktikz/gui.py", line 39, in __init__
    self.mainUi = loadUi(ui_path("quicktikz","main.ui"), self)
  File "/home/guinslym/anaconda3/lib/python3.6/site-packages/PyQt5/uic/__init__.py", line 226, in loadUi
    return DynamicUILoader(package).loadUi(uifile, baseinstance, resource_suffix)
  File "/home/guinslym/anaconda3/lib/python3.6/site-packages/PyQt5/uic/Loader/loader.py", line 72, in loadUi
    return self.parse(filename, resource_suffix, basedir)
  File "/home/guinslym/anaconda3/lib/python3.6/site-packages/PyQt5/uic/uiparser.py", line 1003, in parse
    document = parse(filename)
  File "/home/guinslym/anaconda3/lib/python3.6/xml/etree/ElementTree.py", line 1196, in parse
    tree.parse(source, parser)
  File "/home/guinslym/anaconda3/lib/python3.6/xml/etree/ElementTree.py", line 586, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/guinslym/anaconda3/lib/python3.6/site-packages/quicktikz/main.ui'
```

Also I would like to start creating pyQt software (or package) I would like to know what did you use to create your *.ui file? Any tutorial that I can find onlline?

**Comment by a358003542** [comment]
pyqt5 and python3 is a very convenient way to start your project.  just simplely pip3 install pyqt5 and you can start it.

the ui file is created by the QT designer. you can find it on the QT website. and the qrc file is the resource file solution,  the pyqt the pyrcc5 can process it , and the ts file is created by pylupdate5 , and you can also use the Qt linguit tools to process the translation job.

i am not familiar with the english tutorial , you can search it on web . i believe you can have a goog start with it.

**Comment by a358003542** [comment]
@guinslym  the mian.ui problem i just have fixed it , please update the source code. there is a problem on version before .   i upload a version 0.8 instead of 0.0.8 . so please  install like that :  

```
python3 setup.py sdist

pip3 install dist\what..tar.gz
```
